### ðŸ§  Challenge #4: Data Exploration

Look at the Machine Learning Operations life cycle diagram below.

Understand the **Product Initiation** and **Data Exploration** phases.
Write code to read and load the `titanic data` data set into a Pandas-based data structure, `interpret_median`, understand the `meta data` and print the **initial exploration** like the top 5 rows and the `description`. Then make an interpretation of the data set and prepare a pitch about the use case. 

ðŸ“Œ **Instructions**:
- Read and load the data set.
- `Interpret` the data set, its attributes and their respective measures of `Central Tendency`.
- Prepare a 50-word summary of the `Use Case` described by the `Data Set`

In [10]:
import pandas as pd

class TitanicDataExplorer:
    def __init__(self, titanic_data: str):
        """Initialize with Titanic dataset file path."""
        self.titanic_data = titanic_data
        self.df = None

    def load_data(self):
        """Load Titanic dataset into Pandas DataFrame."""
        self.df = pd.read_csv(self.titanic_data)
        return self.df

    def explore_data(self):
        """Print top 5 rows and dataset info."""
        print("ðŸ”¹ Top 5 Rows:")
        print(self.df.head(), "\n")

        print("ðŸ”¹ Metadata:")
        print(self.df.info(), "\n")

        print("ðŸ”¹ Descriptive Statistics:")
        print(self.df.describe(include="all"), "\n")

    def central_tendency(self):
        """Calculate mean, median, and mode."""
        mean_vals = self.df.mean(numeric_only=True)
        median_vals = self.df.median(numeric_only=True)
        mode_vals = self.df.mode().iloc[0]

        print("ðŸ”¹ Mean Values:\n", mean_vals, "\n")
        print("ðŸ”¹ Median Values:\n", median_vals, "\n")
        print("ðŸ”¹ Mode Values:\n", mode_vals, "\n")

        return {"mean": mean_vals, "median": median_vals, "mode": mode_vals}


# ------------------------------
# ðŸš€ Run the class
# ------------------------------
if __name__ == "__main__":
    # Replace with the actual Titanic dataset file path
    explorer = TitanicDataExplorer("titanic_data.csv")
    
    # Load data
    df = explorer.load_data()
    
    # Explore dataset
    explorer.explore_data()
    
    # Central tendency analysis
    interpret_median = explorer.central_tendency()

ðŸ”¹ Top 5 Rows:
   Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...
2         1       3                              Miss. Laina Heikkinen
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle
4         0       3                            Mr. William Henry Allen

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare
0    male  22.0                        1                        0   7.2500
1  female  38.0                        1                        0  71.2833
2  female  26.0                        0                        0   7.9250
3  female  35.0                        1                        0  53.1000
4    male  35.0                        0                        0   8.0500

ðŸ”¹ Metadata:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Survived                 887 non-null    int64
 1   Pclass                   887 non-null    int64
 2   Name                     887 non-null    object
 3   Sex                      887 non-null    object
 4   Age                      887 non-null    float64
 5   Siblings/Spouses Aboard  887 non-null    int64
 6   Parents/Children Aboard  887 non-null    int64
 7   Fare                     887 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.6+ KB
None

ðŸ”¹ Descriptive Statistics:
          Survived      Pclass                    Name   Sex         Age  \
count   887.000000  887.000000                     887   887  887.000000
unique         NaN         NaN                     887     2         NaN
top            NaN         NaN  Mr. Owen Harris Braund  male         NaN
freq           NaN         NaN                       1   573         NaN
mean      0.385569    2.305524                     NaN   NaN   29.471443
std       0.487004    0.836662                     NaN   NaN   14.121908
min       0.000000    1.000000                     NaN   NaN    0.420000
25%       0.000000    2.000000                     NaN   NaN   20.250000
50%       0.000000    3.000000                     NaN   NaN   28.000000
75%       1.000000    3.000000                     NaN   NaN   38.000000
max       1.000000    3.000000                     NaN   NaN   80.000000

        Siblings/Spouses Aboard  Parents/Children Aboard       Fare
count                887.000000               887.000000  887.00000
unique                      NaN                      NaN        NaN
top                         NaN                      NaN        NaN
freq                        NaN                      NaN        NaN
mean                   0.525366                 0.383315   32.30542
std                    1.104669                 0.807466   49.78204
min                    0.000000                 0.000000    0.00000
25%                    0.000000                 0.000000    7.92500
50%                    0.000000                 0.000000   14.45420
75%                    1.000000                 0.000000   31.13750
max                    8.000000                 6.000000  512.32920

ðŸ”¹ Mean Values:
 Survived                    0.385569
Pclass                      2.305524
Age                        29.471443
Siblings/Spouses Aboard     0.525366
Parents/Children Aboard     0.383315
Fare                       32.305420
dtype: float64

ðŸ”¹ Median Values:
 Survived                    0.0000
Pclass                      3.0000
Age                        28.0000
Siblings/Spouses Aboard     0.0000
Parents/Children Aboard     0.0000
Fare                       14.4542
dtype: float64

ðŸ”¹ Mode Values:
 Survived                                           0.0
Pclass                                             3.0
Name                       Capt. Edward Gifford Crosby
Sex                                               male
Age                                               22.0
Siblings/Spouses Aboard                            0.0
Parents/Children Aboard                            0.0
Fare                                              8.05
Name: 0, dtype: object

#### âœ… Challenge #4: Summary of the Use Case

Use Case Summary

The Titanic dataset supports predictive modeling of passenger survival using demographic, socioeconomic, and travel attributes. By exploring central tendencies like age, fare, and class, patterns in survival emerge. This use case illustrates real-world classification problems, enabling data-driven insights for safety strategies and risk assessment in transportation and beyond.

### ðŸ§  Challenge #5: Object-Oriented Python

Re-use the code you write for challenges 1, 2 and 3, and the `interpret_mean`, `interpret_median`, and `interpret_mode` and make them **attributes** of a new class called `CentralTendency`and the `Titanic data set`.

ðŸ“Œ **Instructions**:
- Define the class in the code cell below.
- Add a `constructor` and the three attributes to the class, each one with the proper parameters and return values.
- After the class, instantiate an object of class `CentralTendency` called `stats`
- Feed the data in the `df` data structure to the object, and have the code print the mean, median, and mode.

#### ðŸ’» Write the code in the cell below:

In [15]:
#Central Tendency Calculator
import pandas as pd

class CentralTendency:
    def __init__(self, df: pd.DataFrame):
        """Initialize with a DataFrame."""
        self.df = df

    def interpret_mean(self, column: str):
        """Calculate mean of a column."""
        return self.df[column].mean()

    def interpret_median(self, column: str):
        """Calculate median of a column."""
        return self.df[column].median()

    def interpret_mode(self, column: str):
        """Calculate mode of a column."""
        mode_val = self.df[column].mode()
        return mode_val[0] if not mode_val.empty else None


# ------------------------------
# ðŸš€ Example usage
# ------------------------------
if __name__ == "__main__":
    # âœ… Load Titanic dataset with the correct filename
    df = pd.read_csv("titanic_data.csv")

    # Select main features for analysis
    features = ["Survived", "Pclass", "Age", "Fare"]

    # Instantiate CentralTendency
    stats = CentralTendency(df)

    # Collect results
    results = {
        "Feature": [],
        "Mean": [],
        "Median": [],
        "Mode": []
    }

    for feature in features:
        results["Feature"].append(feature)
        results["Mean"].append(stats.interpret_mean(feature))
        results["Median"].append(stats.interpret_median(feature))
        results["Mode"].append(stats.interpret_mode(feature))

    # Create summary table
    summary_table = pd.DataFrame(results)
    print(summary_table)

    Feature       Mean   Median   Mode
0  Survived   0.385569   0.0000   0.00
1    Pclass   2.305524   3.0000   3.00
2       Age  29.471443  28.0000  22.00
3      Fare  32.305420  14.4542   8.05